# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "ubuntu_vagrant" do |defined|
    defined.vm.box = "ubuntu"
    defined.vm.hostname = "server"
    defined.vm.provider "virtualbox" do |virtual_box|
      virtual_box.gui = false
      virtual_box.memory = "1024"
      virtual_box.cpus = 1
      virtual_box.name = "ubuntu_vagrant"
      virtual_box.customize ["modifyvm", :id, "--nictype1", "virtio"]
      virtual_box.customize ["modifyvm", :id, "--nictype2", "virtio"]
      virtual_box.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      virtual_box.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  defined.vm.network "public_network", ip: "192.168.85.85", :nictype => 'virtio', :adapter => 2
  end
end
